### ISSUE TITLE
Out of sync after upgrade to 2.0

### ISSUE THREAD

**Issue by c0mm0n** [Roeshambo/MonolithDKP#155]
Hi,

We are 3 officers online.
We synced and were in sync (i'm lootmaster so broadcasted)

We all 3 updated to 2.0
I migrated, they both deleted.

Then it worked, DKPs tables were synced between all 3. DKP "works".

BUT, i still have a "red status"

"One of more of your tables are out of date"

Missing entries
Me: 25

I dont get how I can have missing entries from myself?
How can we fix this?

I'm lootmaster and only DKP editor for weeks.

**Comment by c0mm0n** [comment]
<img width="585" alt="image" src="https://user-images.githubusercontent.com/1181493/70392207-bb5b2180-19dd-11ea-8a47-54f009969c6b.png">

**Comment by c0mm0n** [comment]
Did some further testing, everything seems to work, just those "25 missing from myself" display.

**Comment by Roeshambo** [comment]
Please post your saved variables file

**Comment by c0mm0n** [comment]
Here it is (this is the one before migration)
[MonolithDKP.lua.txt](https://github.com/Roeshambo/MonolithDKP/files/3936679/MonolithDKP.lua.txt)

**Comment by Roeshambo** [comment]
Ok can you post the one post migration as well.

**Comment by Roeshambo** [comment]
And did you use 2.0.3 or 2.0.4 to migrate?

**Comment by c0mm0n** [comment]
I auto updated from curse, seems to be 2.0.4 though addons itself is written 2.0.3 on top. (prob a glitch)

This is the v2 file, but we just raided so you have more events just added, sorry.

**Comment by c0mm0n** [comment]
[MonolithDKP.lua.txt](https://github.com/Roeshambo/MonolithDKP/files/3937043/MonolithDKP.lua.txt)

**Comment by Roeshambo** [comment]
Curious. It seems your migration missed some entries entirely... Delete the {MonDKP=OfficerName} tag from your GM note and then close your client and delete the current saved variables file and replace it with the premigrated copy. And do the migration again. Then after it reloads from the migration, post that saved variables file it creates. Everyone else will have to wipe their tables as all entries will be reindexed (button to do so is on the options tab)

**Comment by Roeshambo** [comment]
Actually scratch that... Hold on. I think I see why it got screwy.

**Comment by Roeshambo** [comment]
For some reason you've got several entries with identical time stamps. Do the steps I suggested above. But before you do, replace your Migration.lua file with the one I'm posting below. It'll be located in the MonolithDKP\Modules folder. Make sure to rename it to remove the .txt from the end.
[Migration.lua.txt](https://github.com/Roeshambo/MonolithDKP/files/3937082/Migration.lua.txt)

**Comment by Squigglymoo** [comment]
Roeshambo, We are having the same problem, how can we solve this? would you like our Saved Variable files?

**Comment by Roeshambo** [comment]
You're seeing yourself as having missing entries created by yourself?

**Comment by Squigglymoo** [comment]
I have missing entries from my GM, 19 missing and he has 19 missing entries from himself.

**Comment by Roeshambo** [comment]
Ok. Have your GM delete his public note. Roll back his saved variables file to premigration. And delete his MonolithDKP addon folder. Redownload it from here (he must remove the -master from the end of the folder name after downloading). Then have him redo the migration. Everyone else will wipe their tables and receive the new information migrated.

**Comment by c0mm0n** [comment]
so @Roeshambo 

Just to have it clear.
0. Update the addon with the migration.lua you posted above
1. Delete the GM entry
2. Restore the pre migration data
3. Re migrate

We got new logs just now, it's a bit difficult to remigrate, you dont have any workaround avoiding a rollback ? (even if i have to do manually)

Thx a lot for your help

**Comment by Squigglymoo** [comment]
@Roeshambo My GM is advising there is no prompt for him to start the migration again, may i request the command for this?

**Comment by Roeshambo** [comment]
He has to roll back his Saved Variables file to the premigrated version. Make sure he closes his client before doing so. You can't change the SavedVariables file if the client is open. He won't be able to open the migration window if he doesn't. Did that fix your issue @c0mm0n ?

**Comment by c0mm0n** [comment]
I'm in MC atm :D 

Will check after.

So no other option then a rollback ? Like I cant just re input those 25 missing manually ? (cause i'll have to reinput the full MC log anyway if I rollback)

**Comment by Roeshambo** [comment]
After your MC, save the current file you're using (with the new MC entries) and then roll back and remigrate with the new version. Then post the one with the MC entries as well as the newly migrated one. I'll manually merge them for you.

**Comment by Squigglymoo** [comment]
@Roeshambo it still did not work for him, so we both rolled everything back, I then completed the migration. However it still shows the GM Missing 19 Entries. which its now saying im out of date for.

**Comment by Squigglymoo** [comment]
If it helps, 19 entries was the exact amount of entries from our previous MC run...11 drops 8 bosses, the GM was also not there for this run.

**Comment by Roeshambo** [comment]
Post the file you used to migrate (before it was migrated)

**Comment by Squigglymoo** [comment]
[MonolithDKP.txt.zip](https://github.com/Roeshambo/MonolithDKP/files/3937144/MonolithDKP.txt.zip)

**Comment by Squigglymoo** [comment]
We have managed to make it work correctly, by both of using my Original Saved Variables before migration, after migration its working fine....however.....all the figures have doubled. any quick fix for this?

**Comment by Roeshambo** [comment]
@Squigglymoo I just migrated that file fine on my side. Make sure you download the newest version here on Git (i uploaded a fix not too long ago). Close your client entirely. And replace the current SavedVariables file with the one you just posted. Then login and migrate it (you may need to delete GM pub note to do so). Make sure all other officers wipe their tables first or else they may broadcast old entries to you.

**Comment by Roeshambo** [comment]
No, doubled entries means two separate people migrated and merged entries (this is the explicit reason only one person can execute the migration). All entries are given an index based on that officers character name. If two people migrate, even if the entries are identical, they have different indexes. So they get broadcasted.

**Comment by Squigglymoo** [comment]
May i ask how we can fix this....and then i will migrate again using the file i linked to you as it works fine for you. i will delete and install the new addon from this website.

**Comment by Roeshambo** [comment]
Just have all officers wipe their tables while you're offline and you load up that file. Then after they've wiped, login and migrate. It should then give all of the officers the new tables.

**Comment by Roeshambo** [comment]
After officers are taken care of, any other members that have incorrect data just need to wipe and request new data.

**Comment by Roeshambo** [comment]
If you're still having troubles after that, give me your characters name and have all officers wipe their tables and I'll migrate it for you. The most important part is the other officers all have their tables wiped. Or else they may sync up with you and send you old data that you had sent them.

**Comment by Squigglymoo** [comment]
I believe that has fixed it....we are just getting one more officer to login to make sure everything is ok.

**Comment by Squigglymoo** [comment]
This has now worked, Thank you so much @Roeshambo for the amazing work.

**Comment by Roeshambo** [comment]
Good to hear. I apologize for getting your tables jacked up with the botched release last month :p

**Comment by c0mm0n** [comment]
@Roeshambo i'm about to do it.

To avoid any officers sync issues, isnt it safer to demote them until i'm sure they have the update from me ? Then repromote them ?

**Comment by Roeshambo** [comment]
Yes that would prevent them from sending you any data. They would have to relog after you demote them for the addon to acknowledge they are not officers.

**Comment by c0mm0n** [comment]
So i did all this, only online officers were not demoted. But i still have 14 missing entries (after doing the migration from the pre migration lua)

<img width="607" alt="image" src="https://user-images.githubusercontent.com/1181493/70397437-7b626180-1a12-11ea-9d3a-1718b1f28d73.png">

**Comment by c0mm0n** [comment]
My addon code is the latest from github

**Comment by Roeshambo** [comment]
I uploaded a new version with the same version number a bit ago. I'd recommend reinstalling it and do the migration.

**Comment by c0mm0n** [comment]
My code is from 20 mins ago, i downloaded from github just before doing the migration.

I'm gonna try again let's see.

**Comment by c0mm0n** [comment]
Same issue, now we only 2 officers in guild, me and GM : ))

<img width="614" alt="image" src="https://user-images.githubusercontent.com/1181493/70397661-73a3bc80-1a14-11ea-8ae0-5081d28ac2de.png">

**Comment by c0mm0n** [comment]
Before migration

<img width="506" alt="image" src="https://user-images.githubusercontent.com/1181493/70397707-d85f1700-1a14-11ea-9ce9-94d2dcddce83.png">

**Comment by c0mm0n** [comment]
After

<img width="600" alt="image" src="https://user-images.githubusercontent.com/1181493/70397723-edd44100-1a14-11ea-9496-b79ae69e992d.png">

**Comment by c0mm0n** [comment]
File after migration with latest code.
Pre migration file is still the same (see above)

[MonolithDKP.lua.txt](https://github.com/Roeshambo/MonolithDKP/files/3937271/MonolithDKP.lua.txt)

**Comment by c0mm0n** [comment]
But, now this is interesting

`MonDKP_Errant = {
}`

So i dont have any errants, what's the 14 entries coming from ?

**Comment by Roeshambo** [comment]
Reload your UI and then look at the file. If the MonDKP_Meta_Remote has a higher value for you than the number of entries (Compare MonDKP_Meta to MonDKP_Meta_Remote) it means someone else thinks you have more entries than you do. You broadcasting to them should fix it.

**Comment by c0mm0n** [comment]
MonDKP_Meta: 178
MonDKP_Meta_Remote: 188

So for you errants being empty means everything is fine and will be fixed by rebroadcasting, correct?

**Comment by Roeshambo** [comment]
The errant table logs any entries missing that fall between the "current" and "lowest" value for each officer. So if it's empty, then you have all entries known.

**Comment by Roeshambo** [comment]
The remote table stores highest known among others in the guild. It's how you identify if there are newer entries somewhere in the guild. So someone else might think there are more

**Comment by c0mm0n** [comment]
Ok so I just have everyone wipe their tables or delete .lua and i'm fine ?

**Comment by c0mm0n** [comment]
So now I have this

Migrated from 4pm backup
[MonolithDKP_migrated.lua.txt](https://github.com/Roeshambo/MonolithDKP/files/3937300/MonolithDKP_migrated.lua.txt)

The file with our MC run today where I need to merge changes into the one above.
[MonolithDKP_mc.lua.txt](https://github.com/Roeshambo/MonolithDKP/files/3937302/MonolithDKP_mc.lua.txt)

Can you help me retrieve the logs from 2nd file to 1st ?

Thx again, i'll donate for your time and the addon.

**Comment by Roeshambo** [comment]
I just merged them and remigrated it. Just waiting for validation to run. All players will need to wipe their tables. But most importantly the officers. Other players can wipe them as needed, but it's important that all officers wipe theirs. When I upload the file, close your client and replace your current saved variables with that one. Then login and it'll distribute those new entries to other officers.

**Comment by Roeshambo** [comment]
Make sure to remove the .txt and have your client completely closed before putting it into the folder. And again, make sure all other officers wipe their tables first. If they have any entries from the previous migration, they will likely send them to you. Which would create problems.
[MonolithDKP.lua.txt](https://github.com/Roeshambo/MonolithDKP/files/3937323/MonolithDKP.lua.txt)

**Comment by Roeshambo** [comment]
If this does not resolve your issue please reopen the ticket and let me know what isn't working properly.

**Comment by c0mm0n** [comment]
Problem solved, THX A LOT @Roeshambo !

<img width="343" alt="iSN 2019-12-09 à 09 44 03" src="https://user-images.githubusercontent.com/1181493/70420825-d1fa8a80-1a68-11ea-869b-988d8463b2c6.png">

**Comment by c0mm0n** [comment]
I have to reopen this 😭

So this morning I login with your backup, all officers are demoted but me (and GM).
GM is offline (Zuljen). I'm green, people sync, all is good.

<img width="355" alt="iSN 2019-12-09 à 10 50 17" src="https://user-images.githubusercontent.com/1181493/70429696-6a990680-1a79-11ea-9ce4-d0ac14366aa8.png">

GM comes online having deleted his lua file before (we both run latest 2.0.5), i update him but then:

<img width="334" alt="iSN 2019-12-09 à 11 32 18" src="https://user-images.githubusercontent.com/1181493/70429660-548b4600-1a79-11ea-90c8-ecf88a5bc7cf.png">

<img width="393" alt="iSN 2019-12-09 à 11 37 15" src="https://user-images.githubusercontent.com/1181493/70429464-e5aded00-1a78-11ea-8b24-262f284804a2.png">

From there we tried the other way around: 
- He demoted me (so only GM is officer)
- i wiped all data and files
- i login, he updated me => same result

We tried again 3/4 times the other way around (me updating him with blank data), we got to both green and then again the same status.

<img width="393" alt="iSN 2019-12-09 à 11 37 15" src="https://user-images.githubusercontent.com/1181493/70429559-12fa9b00-1a79-11ea-83ab-05f2c2853671.png">

Must be a little issue somewhere... we double checked everything, noone else is officer (most are offline on this monday morning).

**Comment by c0mm0n** [comment]
@Roeshambo 
"you cannot re-open your own issues if a repo collaborator closed them"

I cant reopen ticket.

**Comment by Roeshambo** [comment]
No worries. Most likely just a hang up and nothing actually missing. Can you please, if possible, post both his and your sv file?

**Comment by c0mm0n** [comment]
Thx @Roeshambo 

So we did the operation again.

Me with the file you sent, GM starting empty.
- I launch => green
- Updating GM
- Then GM is green, i'm red and the 4 missing entries for GM

Here are the files after those steps (the sync between me and GM was ended).

[MonolithDKP_Officer.lua.txt](https://github.com/Roeshambo/MonolithDKP/files/3941875/MonolithDKP_Officer.lua.txt)
[MonolithDKP_GM.lua.txt](https://github.com/Roeshambo/MonolithDKP/files/3941876/MonolithDKP_GM.lua.txt)

**Comment by Roeshambo** [comment]
Ok So here's what's happening. Both of your tables are correct and you have all data. If you look in your file, near the bottom, you'll see a MonDKP_Meta_Remote table. How that works, is when you sync with the guild, you request meta tables from everyone in the guild. If you receive a table that has a higher value than what you have, it's noted in the Meta_Remote (Meta_Remote basically just notes what the highest known index is in the guild) so you know you're missing entries from that officer. Your Meta_Remote says Zuljen has 3 Loot entries and 1 DKP entry. That's obviously not true. But someone in your guild thinks it is. So at least one player in your guild still has old tables from before we fixed the migration. The newest version takes steps to rectify that if it occurs (if someone thinks Zuljen has more entries while syncing with Zuljen, he basically responds with "No, this is how many i actually have, delete anything you thought I had"). But everyone must be on that newer version. So all of your data is correct. You just have to get the non-officer members to wipe their tables and request the new data. Then you can delete your MonDKP_Meta_Remote table and you'll be fine. Hopefully that book makes sense.

**Comment by c0mm0n** [comment]
Ok i got it, i'm trying to have people wipe their table.

But now I have another issue.

All the events from sunday evening (the things you merged for me) are NOT taken into the total.

I have HTML backup from 4.12, one guy (Talic) has 110 DKP. Then he does the raid, earns 35 DKP.
Now his total is still 110 DKP. I tried to reload / relogin, etc, totals are still wrong.

**Comment by Roeshambo** [comment]
That's not a problem. Right click your table and select validate tables. It'll take a few minutes to run but it recalculates all data based on the history

**Comment by c0mm0n** [comment]
Ok thx doing it, started to panic.

I'll close this issue and reopen if needed.

For the original problem, an option that would kinda allow us/me to force update everyone would be nice.

Thx again for your help.

**Comment by Roeshambo** [comment]
During a sync with the new version it should force them to the correct value. But they have to have that version as well

**Comment by c0mm0n** [comment]
Nice, is it on curse already ?

**Comment by Roeshambo** [comment]
Yes

**Comment by c0mm0n** [comment]
Sorry have to reopen already, Validation doesnt work, total stays wrong.

I took this simple user (my alt) as a test case.

![image](https://user-images.githubusercontent.com/1181493/70553411-5a695000-1b7b-11ea-84bb-223491c594a0.jpeg)

**Comment by c0mm0n** [comment]
Seems I found : )

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/1181493/70553578-ad430780-1b7b-11ea-8912-730727a66aad.png">

**Comment by c0mm0n** [comment]
This entry is the problem, can I
1. mark it hidden false
2. delete it from UI ?

**Comment by Roeshambo** [comment]
Ah, yes I completely forgot about that. During the migration, if the history adds up incorrectly in comparison to the table, it creates an entry to compensate (the assumption was that the DKP table would be correct but history entries may have been lost in past versions that were slower to broadcast). Post that file and I'll fix it for you manually. Indexes need to be moved if there's any entries above it. So wanna get it right for ya.

**Comment by c0mm0n** [comment]
Ok thx, i thought doing it with UI would do it cleanly 

[MonolithDKP.lua.txt](https://github.com/Roeshambo/MonolithDKP/files/3946410/MonolithDKP.lua.txt)

**Comment by Roeshambo** [comment]
Well actually, I suppose you could do that now that I think of it. That way no one would need to wipe tables since everything is reindexed. They'll just receive the new entry countering that one.  Just delete the "hidden" key entirely and load it up in game and then it should show in the DKP history. I haven't tried deleting that within the UI but it should work the same as a decay. If it doesn't for whatever reason, just say so and I'll fix it with the file you just posted.

**Comment by c0mm0n** [comment]
Ok it worked 👍

Now I have 1 missing entry from myself. This will be fixed when people update addon?

<img width="601" alt="image" src="https://user-images.githubusercontent.com/1181493/70556123-84714100-1b80-11ea-83cf-ba0cead17588.png">

**Comment by Roeshambo** [comment]
Reload and post your SV file plz. Just want to make sure

**Comment by c0mm0n** [comment]
[MonolithDKP2.lua.txt](https://github.com/Roeshambo/MonolithDKP/files/3946630/MonolithDKP2.lua.txt)

**Comment by Roeshambo** [comment]
Ok I think I see what went wrong. It appears you removed the entry entirely from the file which created a missing index. Only part that should have been removed was the "["hidden"] = true," portion of the Migration Correction entry. Then the entry deleted within the game. I'll get that fixed up for you really quick.

**Comment by c0mm0n** [comment]
I misunderstood.
I'll fix it I have backup.

**Comment by Roeshambo** [comment]
No worries. I'm fixing it so as to not create unintentional entries.

**Comment by Roeshambo** [comment]
If you roll back to your backup you may have extra entries floating around in the guild.

**Comment by Roeshambo** [comment]
Just replace yours with this. 
[MonolithDKP.lua.txt](https://github.com/Roeshambo/MonolithDKP/files/3946674/MonolithDKP.lua.txt)

**Comment by Roeshambo** [comment]
You may also need to run the table validation again just in case.

**Comment by Roeshambo** [comment]
And if any members have incorrect numbers, just have them wipe their table and sync

**Comment by c0mm0n** [comment]
Seems validation is ok. Totals are correct.

Now i'm here

<img width="618" alt="image" src="https://user-images.githubusercontent.com/1181493/70560082-3f510d00-1b88-11ea-9501-ff693eb2f366.png">

**Comment by c0mm0n** [comment]
<img width="601" alt="image" src="https://user-images.githubusercontent.com/1181493/70560190-6f98ab80-1b88-11ea-893b-560d369dd269.png">

All good, so still the 4 missing for GM. Still asking people to wipe tables.

**Comment by Roeshambo** [comment]
Ok good. Sorry about all that. Know the migration can be a headache. But once over that hump it should be all smooth from then out  :p.  if ya need any additional help please let me know. Just so you're clear on how that'll clear up. When Zuljen himself is online during a sync, when he broadcasts his tables, it should correct everyone elses remote values. So it'll only actually clear up if he's online when a sync occurs.

**Comment by c0mm0n** [comment]
No worries man, thx a lot for the help.

Ok nice i'll have him online tonight

I close, to be followed : )

**Comment by Roeshambo** [comment]
Oh, one additional note. If any of your officers still have old data, i would recommend they delete their saved variables file before logging in. If they have old data still and login, they may send it to you. Not sure if you've already sent them the new info or not. Just wanted to help make sure you don't have any additional issues.

**Comment by c0mm0n** [comment]
Damn too late :D

So Zuljen came, and the sync went, and now we have this.

So should I have him wipe his file tmr and resync from me and done?

[MonolithDKP_GM.lua.txt](https://github.com/Roeshambo/MonolithDKP/files/3947268/MonolithDKP_GM.lua.txt)
[MonolithDKP_Officer.lua.txt](https://github.com/Roeshambo/MonolithDKP/files/3947269/MonolithDKP_Officer.lua.txt)

**Comment by Roeshambo** [comment]
Yes. Unfortunately you'll also have to have all other officers that may have received his broadcast wipe theirs as well. I'm going to write an executable script tonight and push out that will allow the GM to execute a reindexing and cleanup as well as tell everyone else i the guild to wipe their tables. Also going to shut off automatic syncing. Seems to be causing more problems than it's worth. Just roll back to the file I gave you and after they've wiped, resync from that and you should be good. Probably best to get all officers and GM online at the same time when you do that.

**Comment by c0mm0n** [comment]
Thx i just got GM online, and asked him to wipe while I restored mine, waiting for result.

**Comment by c0mm0n** [comment]
Ok the sync happened, I still have 4 missing for GM, now he has 71 missing from me : )

What's the current way of fixing it ?

**Comment by Roeshambo** [comment]
What that means is there's someone in the guild that thinks more entries exist than really do and they don't have an updated version that corrects it on their side 0_o. Their tables simply need wiping.

**Comment by Roeshambo** [comment]
If you and the others in the guild are on the newest version it corrects itself after they've wiped their tables. The first versions didn't have anything to correct that issue unfortunately. Your data isn't incorrect. There's just someone in your guild that thinks it is. I would have everyone wipe their tables and update and once that bad data is out of circulation you should be all good. It's just the data that was passed from initial migration that is lingering.

**Comment by c0mm0n** [comment]
I got green today \o/

So now let's say i'm green, GM is not green, he just wipes and solved?

**Comment by Roeshambo** [comment]
He can do that and ya he should get green. Unless there is someone online part of the sync that updates him that has old data. It's just that nasty old data that's a pain to get rid of if everyone doesn't wipe their tables :/. Fortunately, that also means it's difficult to lose pretty much any data lol.

**Comment by c0mm0n** [comment]
Ok good, but as of now can non officers still pollute ?

Yes we kinda relaxed about restoring backups now, process is mastered :D

**Comment by Roeshambo** [comment]
No only officers can broadcast entries. Only thing non officers will send you is how many entries their meta table says they have. That's how you find out an offline officer created entries while you were offline.
